# -*- coding: utf-8 -*-
"""5243hw4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kYf4p0EF7f-Yiwq1FfA_leDPyXBCARK8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score


# Euclidean distance calculation
def euclidean_distance(pt1, pt2):
    return sum((a - b) ** 2 for a, b in zip(pt1, pt2)) ** 0.5

# Calculates SSEs and SSB
def calculate_sse_ssb(data, labels, centers, overall_mean):
    sse = {i: 0 for i in range(len(centers))}
    overall_sse = 0
    ssb = 0

    for i, point in enumerate(data):
        cluster_idx = labels[i]
        center = centers[cluster_idx]

        # Calculate SSE
        sq_dist = sum((a - b) ** 2 for a, b in zip(point, center))
        sse[cluster_idx] += sq_dist
        overall_sse += sq_dist

    for i, center in enumerate(centers):
        # Calculate SSB
        cluster_size = list(labels).count(i)
        sq_dist_mean = sum((a - b) ** 2 for a, b in zip(center, overall_mean))
        ssb += cluster_size * sq_dist_mean

    return sse, overall_sse, ssb

# Custom k-means algorithm
def custom_kmeans(data, k, max_iters=100):
    np.random.seed(42)
    # Randomly initialize centroids using data points
    initial_indices = np.random.choice(len(data), k, replace=False)
    centroids = [data[i] for i in initial_indices]
    for _ in range(max_iters):
        clusters = []
        for point in data:
            distances = [euclidean_distance(point, centroid) for centroid in centroids]
            min_dist_idx = distances.index(min(distances))
            clusters.append(min_dist_idx)

        # Update centroids
        new_centroids = []
        for i in range(k):
            cluster_points = [data[j] for j in range(len(data)) if clusters[j] == i]
            if len(cluster_points) > 0:
                # Calculate mean for each dimension
                new_centroid = [sum(dim) / len(dim) for dim in zip(*cluster_points)]
                new_centroids.append(new_centroid)
            else:
                new_centroids.append(centroids[i]) # Keep old centroid if empty

        if centroids == new_centroids:
            break
        centroids = new_centroids

    return np.array(clusters), centroids

# Call the custom k-means algorithm for each dataset
def analyze_dataset_custom(df, feature_cols, true_label_col, k, dataset_name):
    print(f"\nAnalysis for {dataset_name} (k={k}):")
    data = df[feature_cols].values.tolist()
    overall_mean = [sum(dim) / len(dim) for dim in zip(*data)]

    # True cluster analysis
    if true_label_col in df.columns:
        true_labels = df[true_label_col].values
        unique_true = np.unique(true_labels)
        true_centers = []
        for label in unique_true:
            cluster_pts = [data[i] for i in range(len(data)) if true_labels[i] == label]
            true_centers.append([sum(dim)/len(dim) for dim in zip(*cluster_pts)])

        # Map true labels to 0-indexed for function compatibility
        label_map = {val: idx for idx, val in enumerate(unique_true)}
        mapped_true_labels = [label_map[val] for val in true_labels]

        true_sse, true_overall_sse, true_ssb = calculate_sse_ssb(data, mapped_true_labels, true_centers, overall_mean)
        print(f"TRUE CLUSTERS -> Overall SSE: {true_overall_sse:.2f}, SSB: {true_ssb:.2f}")

    # Custom k-means
    pred_labels, pred_centers = custom_kmeans(data, k)

    # Output format
    output_df = pd.DataFrame({'Row_ID': df.index, 'Cluster': pred_labels})
    print(f"\nSample Custom k-Means Output:\n{output_df.head()}")

    # SSE/SSB
    pred_sse, pred_overall_sse, pred_ssb = calculate_sse_ssb(data, pred_labels, pred_centers, overall_mean)
    print(f"K-MEANS PREDICTED -> Overall SSE: {pred_overall_sse:.2f}, SSB: {pred_ssb:.2f}")

    # Cross tabulation matrix
    if true_label_col in df.columns:
        print("\nCross-Tabulation Matrix:")
        print(pd.crosstab(df[true_label_col], pred_labels, rownames=['Actual'], colnames=['Assigned']))

    # Generate scatterplots
    if len(feature_cols) >= 2:
        plt.figure(figsize=(8, 6))
        if true_label_col in df.columns:
            sns.scatterplot(x=df[feature_cols[0]], y=df[feature_cols[1]],
                            hue=pred_labels, style=df[true_label_col],
                            palette='deep', s=60)
            plt.title(f"Overlay: True vs k-Means Clusters - {dataset_name} (k={k})")
            plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', title="Color: Assigned\nShape: Actual")
        else:
            sns.scatterplot(x=df[feature_cols[0]], y=df[feature_cols[1]], hue=pred_labels, palette='deep')
            plt.title(f"Custom k-Means (k={k}) - {dataset_name}")

        plt.tight_layout()
        plt.savefig(f"{dataset_name}_k{k}_scatter.png")
        plt.close()

# Uses off the shelf algorithms
def run_off_the_shelf(df, feature_cols, n_clusters, eps=0.5, min_samples=5):
    X = df[feature_cols].values
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # Scikit-learn KMeans
    km = KMeans(n_clusters=n_clusters, random_state=42)
    km_labels = km.fit_predict(X_scaled)

    # DBSCAN
    dbscan = DBSCAN(eps=eps, min_samples=min_samples)
    dbscan_labels = dbscan.fit_predict(X_scaled)

    # Agglomerative Clustering
    agg = AgglomerativeClustering(n_clusters=n_clusters)
    agg_labels = agg.fit_predict(X_scaled)

    return km_labels, dbscan_labels, agg_labels

# Main method to run each algorithm on each dataset
def main():
    # Load Data
    try:
        df_easy = pd.read_csv('TwoDimEasy-1.csv')
        df_hard = pd.read_csv('TwoDimHard-1.csv')
        df_wine = pd.read_csv('winequality-red.csv', sep=';')
    except FileNotFoundError:
        print("File not found")
        return

    # Infer column names for Easy and Hard datasets (assuming X1, X2, and potentially a True_Label col)
    # Adjust indexing based on actual CSV structures
    easy_features = df_easy.columns[:-1] if len(df_easy.columns) > 2 else df_easy.columns
    easy_target = df_easy.columns[-1] if len(df_easy.columns) > 2 else None

    hard_features = df_hard.columns[:-1] if len(df_hard.columns) > 2 else df_hard.columns
    hard_target = df_hard.columns[-1] if len(df_hard.columns) > 2 else None

    # Custom algorithm for each two dimensional dataset
    analyze_dataset_custom(df_easy, easy_features, easy_target, k=2, dataset_name="TwoDimEasy")
    analyze_dataset_custom(df_easy, easy_features, easy_target, k=3, dataset_name="TwoDimEasy")
    analyze_dataset_custom(df_hard, hard_features, hard_target, k=4, dataset_name="TwoDimHard")
    analyze_dataset_custom(df_hard, hard_features, hard_target, k=3, dataset_name="TwoDimHard")
    wine_features = [col for col in df_wine.columns if col != 'quality']
    scaler = StandardScaler()
    wine_scaled_data = scaler.fit_transform(df_wine[wine_features])

    print("\nAnalysis for Wine Dataset:")
    k_values = [2, 4, 6, 8, 10]
    for k in k_values:
        # Using sklearn here to easily extract SSE for quick comparison
        km = KMeans(n_clusters=k, random_state=42)
        preds = km.fit_predict(wine_scaled_data)
        score = silhouette_score(wine_scaled_data, preds)
        print(f"Wine Dataset (k={k}) -> Inertia (SSE): {km.inertia_:.2f}, Silhouette Score: {score:.3f}")

    # Validation against Quality
    km_best = KMeans(n_clusters=6, random_state=42)
    wine_preds = km_best.fit_predict(wine_scaled_data)
    print("\nCross-Tabulation for Wine Dataset (Actual Quality vs Predicted k=6):")
    print(pd.crosstab(df_wine['quality'], wine_preds, rownames=['Actual Quality'], colnames=['Assigned Cluster']))

    # Run off the shelf algorithms
    print("\nOff-the-Shelf Clustering Comparisons:")
    km_lbl, db_lbl, agg_lbl = run_off_the_shelf(df_easy, easy_features, n_clusters=2, eps=0.5)
    print("TwoDimEasy Scikit-learn Silhouette Scores:")
    print(f"K-Means: {silhouette_score(df_easy[easy_features], km_lbl):.3f}")
    if len(set(db_lbl)) > 1:
        print(f"DBSCAN: {silhouette_score(df_easy[easy_features], db_lbl):.3f}")
    print(f"Agglomerative: {silhouette_score(df_easy[easy_features], agg_lbl):.3f}")

if __name__ == "__main__":
    main()